# Generated by Django 6.0.3 on 2026-03-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.FloatField(),
        ),
    ]
